### PR TITLE
Allow to query by tags in es

### PR DESCRIPTION
**Pull request by eruizgar91**
## Description
Add search using tags.
## Is this PR related with an open issue?

Related to Issue #

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Checklist:

- [ ] Follows the code style of this project.
- [ ] Tests Cover Changes
- [ ] Documentation

#### Funny gif

Put a link of a funny gif inside the parenthesis-->

### CODE REVIEW

**Comment by ttmc** [comment]
Does this pull request make any assumptions about whether "tags" is a string or a list/array? [OEP-8](https://github.com/oceanprotocol/OEPs/tree/master/8) currently says that "tags" should be a list/array of strings but it seems the code handling "tags" hasn't been strict about enforcing that.

**Comment by eruizgar91** [comment]
@ttmc we are not enforcing that at the moment. It's something that is going to come when we use plecos to validate the metadata

**Comment by ttmc** [comment]
I guess my question is, does the query

```python
query_result = create_query(query['tags'], index.tags, query_result, OR, MATCH)
```

make an assumption that "tags" is a list or a string?

**Comment by eruizgar91** [comment]
No, it's independant of that

**Pull request merged**
