### PR TITLE
Add elasticsearch plugin implementation

### PR DESCRIPTION
**Pull request by montanaflynn**
## Description

Added elasticsearch plugin implementation

## Is this PR related with an open issue?

Related to Issue https://github.com/oceanprotocol/ocean/issues/171

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Checklist:

- [x] Follows the code style of this project.
- [x] Tests Cover Changes
- [x] Documentation

#### Funny gif

https://i.imgur.com/enwWXbY.gif

### CODE REVIEW

**Comment by montanaflynn** [comment]
TravisCI is missing an environment variable `CODACY_PROJECT_TOKEN`  so the build fails:

https://travis-ci.com/oceanprotocol/oceandb-elasticsearch-driver/jobs/147873160#L418-L437

```

tests/test_plugin.py ......                                              [100%]
========================== 6 passed in 15.98 seconds ===========================
py37 runtests: commands[2] | coverage report
Name                                       Stmts   Miss  Cover
--------------------------------------------------------------
oceandb_elasticsearch_driver/__init__.py       3      0   100%
oceandb_elasticsearch_driver/instance.py      20      1    95%
oceandb_elasticsearch_driver/plugin.py        40      0   100%
--------------------------------------------------------------
TOTAL                                         63      1    98%
py37 runtests: commands[3] | coverage xml
py37 runtests: commands[4] | python-codacy-coverage -r coverage.xml
2018-09-25 19:03:08,157 - ERROR - environment variable CODACY_PROJECT_TOKEN is not defined.
ERROR: InvocationError for command '/home/travis/build/oceanprotocol/oceandb-elasticsearch-driver/.tox/py37/bin/python-codacy-coverage -r coverage.xml' (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py37: commands failed
The command "tox" exited with 1.
Done. Your build exited with 1.
```

**Comment by kremalicious** [comment]
Ooooh, didn't know that, we'll see how we work around that:

> Pull requests sent from forked repositories do not have access to encrypted variables or data.

https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

**Comment by aaitor** [comment]
Hi @montanaflynn , I have disabled codacy in .travis.yml (master branch). I think if you pull this change to your fork and run again, should works.

**Comment by montanaflynn** [comment]
Thanks @kremalicious and @aaitor, I merged latest master, added docstrings and more tests. 

Tests are passing now and code coverage is at 99%! Please review and let me know if it can be merged.

**Comment by innoprenuer** [comment]
Thanks @montanaflynn.  We have started the review of this PR and will comment here once the review is completed.

**Pull request merged**
